name: tests

on: [push]

jobs:
  unit-tests:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run all unit tests
      run: |
        echo Run test
        npm install
        npm run test
#   lint:

#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v1
#     - name: Check for linting
#       run: |
#         echo Run lint
#         npm install
#         npm run lint